### PR TITLE
Item List

### PR DESCRIPTION
**Pull request by Zamam-Moeez**
Item List completed
Implemented as an ArrayList.
Overridden add and remove methods to keep track of a running sum

### CODE REVIEW

**Review by t-rugg — CHANGES_REQUESTED** [review]
for compatibility with the underlying Item class, probably makes more sense to store the sum as an integer amount of cents (look at how it's done in Item.java)

**Comment by Zamam-Moeez** [comment]
> for compatibility with the underlying Item class, probably makes more sense to store the sum as an integer amount of cents (look at how it's done in Item.java)

getValue() in the Item class returns a double, should that be changed to int ?

**Comment by Shlock9** [comment]
yes it should, forgot to change that

**Review by t-rugg — APPROVED** [review]

**Comment by t-rugg** [comment]
addressed and fixed

**Pull request merged**
