### PR TITLE
Delete item from firebase and ItemList

### PR DESCRIPTION
**Pull request by Zamam-Moeez**
Updated method to remove item from ItemList once deleted from firebase.
Added remove(String id) method to ItemList to remove item based on its firebase id.

### CODE REVIEW

**Comment by Zamam-Moeez** [comment]
Working on tests currently, do not merge

**Comment by Zamam-Moeez** [comment]
Ready to merge

**Comment by Zamam-Moeez** [comment]
DONOT MERGE, ADDING FILTERING

**Review by Shlock9 — APPROVED** [review]
Noice and clean

**Pull request merged**
